version: 2

sources:
  - name: staging
    database: LEARN
    schema: TRAINNING 

    tables:
      - name: YELLOW_TRIP_DATA_jjge

      - name: GREEN_TRIP_DATA_jjge

models:
  - name: stg_yellow_trip_data_jjge
    description: ""
    columns:
      - name: tripid
        data_type: varchar
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: vendorid
        data_type: number
        description: ""

      - name: ratecodeid
        data_type: number
        description: ""

      - name: pickup_locationid
        data_type: number
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookups_jjge')
              severity: warn
            

      - name: dropoff_locationid
        data_type: number
        description: ""

      - name: pickup_datetime
        data_type: timestamp_ntz
        description: ""

      - name: dropoff_datetime
        data_type: timestamp_ntz
        description: ""

      - name: store_and_fwd_flag
        data_type: boolean
        description: ""

      - name: passenger_count
        data_type: number
        description: ""

      - name: trip_distance
        data_type: number
        description: ""

      - name: trip_type
        data_type: number
        description: ""

      - name: fare_amount
        data_type: number
        description: ""

      - name: extra
        data_type: number
        description: ""

      - name: mta_tax
        data_type: number
        description: ""

      - name: tip_amount
        data_type: number
        description: ""

      - name: tolls_amount
        data_type: number
        description: ""

      - name: ehail_fee
        data_type: number
        description: ""

      - name: improvement_surcharge
        data_type: number
        description: ""

      - name: total_amount
        data_type: number
        description: ""

      - name: payment_type
        description: ""
        tests: 
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false


      - name: payment_type_description
        data_type: varchar
        description: ""

  - name: stg_green_trip_data_jjge
    description: ""
    columns:
      - name: tripid
        data_type: varchar
        description: ""

      - name: vendorid
        data_type: number
        description: ""

      - name: ratecodeid
        data_type: number
        description: ""

      - name: pickup_locationid
        data_type: number
        description: ""

      - name: dropoff_locationid
        data_type: number
        description: ""

      - name: pickup_datetime
        data_type: timestamp_ntz
        description: ""

      - name: dropoff_datetime
        data_type: timestamp_ntz
        description: ""

      - name: store_and_fwd_flag
        data_type: boolean
        description: ""

      - name: passenger_count
        data_type: number
        description: ""

      - name: trip_distance
        data_type: number
        description: ""

      - name: trip_type
        data_type: number
        description: ""

      - name: fare_amount
        data_type: number
        description: ""

      - name: extra
        data_type: number
        description: ""

      - name: mta_tax
        data_type: number
        description: ""

      - name: tip_amount
        data_type: number
        description: ""

      - name: tolls_amount
        data_type: number
        description: ""

      - name: ehail_fee
        data_type: number
        description: ""

      - name: improvement_surcharge
        data_type: number
        description: ""

      - name: total_amount
        data_type: number
        description: ""

      - name: payment_type
        data_type: number
        description: ""

      - name: payment_type_description
        data_type: varchar
        description: ""
